export enum Role {
  ADMIN = 'ADMINISTRADOR',
  COORD = 'COORDENADOR',
  SOCIO = 'SOCIOPEDAGOGICO',
  NEURO = 'NEUROLOGIA',
  PSICO = 'PSICOPEDAGOGA',
  FINANCEIRO = 'FINANCEIRO',
  OFICINEIRO = 'OFICINEIRO'
}